---
version: '3.4'

services:
  bootnode:
    build:
      context: besu_clique/.
      args:
        BESU_VERSION: 1.3.1
    image: quickstart/besu:1.3.1-clique
    container_name: bootnode
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
      - BESU_GENESIS_FILE_DIRECTORY=/opt/besu/genesis/
    entrypoint: /opt/besu/bootnode_start.sh
    command: &base_options ["--rpc-http-enabled",
              "--rpc-http-api=WEB3,ETH,NET,clique",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-api=WEB3,ETH,NET,clique",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--metrics-enabled",
              "--metrics-host=0.0.0.0",
              "--metrics-port=9545",
              "--host-whitelist=*",
              "--min-gas-price=0"]
    volumes:
      - public-keys:/opt/besu/public-keys/
      - genesis:/opt/besu/genesis/

  node2:
    image: quickstart/besu:1.3.1-clique
    container_name: node2
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
      - BESU_GENESIS_FILE_DIRECTORY=/opt/besu/genesis/
    command: *base_options
    volumes:
      - public-keys:/opt/besu/public-keys/
      - genesis:/opt/besu/genesis/
    depends_on:
      - bootnode

  node3:
    image: quickstart/besu:1.3.1-clique
    container_name: node3
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
      - BESU_GENESIS_FILE_DIRECTORY=/opt/besu/genesis/
    command: *base_options
    volumes:
      - public-keys:/opt/besu/public-keys/
      - genesis:/opt/besu/genesis/
    depends_on:
      - bootnode

  truffle:
    build: ./
    command: sh
    image: truffle
    container_name: truffle
    working_dir: /www
    volumes:
      - ./:/www
    tty: true
    depends_on:
      - node3

volumes:
  public-keys:

  genesis:
