---
version: '3.4'

networks:
  besu-network:
    external: true

services:
  bootnode:
    build:
      context: besu_clique/.
      args:
        BESU_VERSION: 1.3.1
    image: quickstart/besu:1.3.1-clique
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
      - BESU_GENESIS_FILE_DIRECTORY=/opt/besu/genesis/
    entrypoint: /opt/besu/bootnode_start.sh
    command: &base_options ["--rpc-http-enabled",
              "--rpc-http-api=WEB3,ETH,NET,clique",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-api=WEB3,ETH,NET,clique",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--graphql-http-enabled",
              "--graphql-http-host=0.0.0.0",
              "--graphql-http-port=8547",
              "--graphql-http-cors-origins=*",
              "--metrics-enabled",
              "--metrics-host=0.0.0.0",
              "--metrics-port=9545",
              "--host-whitelist=*",
              "--min-gas-price=0"]
    volumes:
      - public-keys:/opt/besu/public-keys/
      - genesis:/opt/besu/genesis/
    networks:
      - besu-network

  node:
    image: quickstart/besu:1.3.1-clique
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
      - BESU_GENESIS_FILE_DIRECTORY=/opt/besu/genesis/
    command: *base_options
    volumes:
      - public-keys:/opt/besu/public-keys/
      - genesis:/opt/besu/genesis/
    depends_on:
      - bootnode
    networks:
      - besu-network

  rpcnode: #  We keep one node named rpcnode to have a specific node to connect the explorer
    image: quickstart/besu:1.3.1-clique
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
      - BESU_GENESIS_FILE_DIRECTORY=/opt/besu/genesis/
    command: *base_options
    volumes:
      - public-keys:/opt/besu/public-keys/
      - genesis:/opt/besu/genesis/
    depends_on:
      - bootnode
    networks:
      - besu-network

  explorer:
    build: block-explorer-light/.
    image: quickstart/block-explorer-light:1.3.1-clique
    depends_on:
      - rpcnode
    ports:
      - "${EXPLORER_PORT_MAPPING:-}80"
    networks:
      - besu-network

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=http://localhost:9090/prometheus
      - --web.route-prefix=/prometheus
    networks:
      - besu-network

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    networks:
      - besu-network

volumes:
  public-keys:

  genesis:

  prometheus:

  grafana:
